# Generated by Django 5.2.9 on 2025-12-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='language',
            field=models.CharField(default='English', max_length=100),
            preserve_default=False,
        ),
    ]
