# Generated by Django 5.2.9 on 2025-12-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_options'),
        ('teacher', '0002_teacher_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ManyToManyField(related_name='groups', to='teacher.teacher'),
        ),
    ]
